import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const allBanks = [
  {
    "id": "islami-bank-bangladesh",
    "name": "Islami Bank Bangladesh PLC",
    "name_bn": "ইসলামী ব্যাংক বাংলাদেশ পিএলসি",
    "short_name": "IBBL",
    "bank_code": "125",
    "swift_code": "IBBLBDDH",
    "head_office": "Islami Bank Tower, 40 Dilkusha C/A, Dhaka-1000",
    "head_office_bn": "ইসলামী ব্যাংক টাওয়ার, ৪০ দিলকুশা সে/এ, ঢাকা-১০০০",
    "website": "https://www.islamibankbd.com",
    "branch_count": 394,
    "established": "1983",
    "type": "Private Commercial"
  },
  {
    "id": "dutch-bangla-bank",
    "name": "Dutch-Bangla Bank PLC",
    "name_bn": "ডাচ-বাংলা ব্যাংক পিএলসি",
    "short_name": "DBBL",
    "bank_code": "090",
    "swift_code": "DBBLBDDH",
    "head_office": "Sena Kalyan Bhaban (5th Floor), 195 Motijheel C/A, Dhaka-1000",
    "head_office_bn": "সেনা কল্যাণ ভবন (৫ম তলা), ১৯৫ মতিঝিল সে/এ, ঢাকা-১০০০",
    "website": "https://www.dutchbanglabank.com",
    "branch_count": 242,
    "established": "1995",
    "type": "Private Commercial"
  },
  {
    "id": "brac-bank",
    "name": "BRAC Bank PLC",
    "name_bn": "ব্র্যাক ব্যাংক পিএলসি",
    "short_name": "BBL",
    "bank_code": "060",
    "swift_code": "BRACBDDH",
    "head_office": "Anik Tower, 220/B, Tejgaon Gulshan Link Road, Tejgaon, Dhaka-1208",
    "head_office_bn": "অনিক টাওয়ার, ২২০/বি, তেজগাঁও গুলশান লিংক রোড, তেজগাঁও, ঢাকা-১২০৮",
    "website": "https://www.bracbank.com",
    "branch_count": 187,
    "established": "2001",
    "type": "Private Commercial"
  },
  {
    "id": "sonali-bank",
    "name": "Sonali Bank PLC",
    "name_bn": "সোনালী ব্যাংক পিএলসি",
    "short_name": "SBL",
    "bank_code": "200",
    "swift_code": "SBNKBDDH",
    "head_office": "35-42, 44 Motijheel Commercial Area, Dhaka-1000",
    "head_office_bn": "৩৫-৪২, ৪৪ মতিঝিল বাণিজ্যিক এলাকা, ঢাকা-১০০০",
    "website": "https://www.sonalibank.com.bd",
    "branch_count": 1230,
    "established": "1972",
    "type": "State-Owned Commercial"
  },
  {
    "id": "eastern-bank",
    "name": "Eastern Bank PLC",
    "name_bn": "ইস্টার্ন ব্যাংক পিএলসি",
    "short_name": "EBL",
    "bank_code": "085",
    "swift_code": "EBLABDDH",
    "head_office": "100 Gulshan Avenue, Dhaka-1212",
    "head_office_bn": "১০০ গুলশান এভিনিউ, ঢাকা-১২১২",
    "website": "https://www.ebl.com.bd",
    "branch_count": 86,
    "established": "1992",
    "type": "Private Commercial"
  },
  {
    "id": "city-bank",
    "name": "The City Bank PLC",
    "name_bn": "দি সিটি ব্যাংক পিএলসি",
    "short_name": "CBL",
    "bank_code": "075",
    "swift_code": "CIITBDDH",
    "head_office": "136, Gulshan Avenue, Gulshan-2, Dhaka-1212",
    "head_office_bn": "১৩৬, গুলশান এভিনিউ, গুলশান-২, ঢাকা-১২১২",
    "website": "https://www.thecitybank.com",
    "branch_count": 133,
    "established": "1983",
    "type": "Private Commercial"
  },
  {
    "id": "prime-bank",
    "name": "Prime Bank PLC",
    "name_bn": "প্রাইম ব্যাংক পিএলসি",
    "short_name": "PBL",
    "bank_code": "170",
    "swift_code": "PRMABDDH",
    "head_office": "119-120 Motijheel C/A, Dhaka-1000",
    "head_office_bn": "১১৯-১২০ মতিঝিল সে/এ, ঢাকা-১০০০",
    "website": "https://www.primebank.com.bd",
    "branch_count": 146,
    "established": "1995",
    "type": "Private Commercial"
  },
  {
    "id": "united-commercial-bank",
    "name": "United Commercial Bank PLC",
    "name_bn": "ইউনাইটেড কমার্শিয়াল ব্যাংক পিএলসি",
    "short_name": "UCB",
    "bank_code": "225",
    "swift_code": "UCBLBDDH",
    "head_office": "Plot 6, Block CWS(A), Gulshan Avenue, Dhaka-1212",
    "head_office_bn": "প্লট ৬, ব্লক সিডব্লিউএস(এ), গুলশান এভিনিউ, ঢাকা-১২১২",
    "website": "https://www.ucb.com.bd",
    "branch_count": 220,
    "established": "1983",
    "type": "Private Commercial"
  },
  {
    "id": "mutual-trust-bank",
    "name": "Mutual Trust Bank PLC",
    "name_bn": "মিউচুয়াল ট্রাস্ট ব্যাংক পিএলসি",
    "short_name": "MTB",
    "bank_code": "150",
    "swift_code": "MTBLBDDH",
    "head_office": "MTB Tower, 26 Gulshan Avenue, Dhaka-1212",
    "head_office_bn": "এমটিবি টাওয়ার, ২৬ গুলশান এভিনিউ, ঢাকা-১২১২",
    "website": "https://www.mutualtrustbank.com",
    "branch_count": 118,
    "established": "1999",
    "type": "Private Commercial"
  },
  {
    "id": "pubali-bank",
    "name": "Pubali Bank PLC",
    "name_bn": "পূবালী ব্যাংক পিএলসি",
    "short_name": "PBL",
    "bank_code": "175",
    "swift_code": "PUBABDDH",
    "head_office": "26 Dilkusha Commercial Area, Dhaka-1000",
    "head_office_bn": "২৬ দিলকুশা বাণিজ্যিক এলাকা, ঢাকা-১০০০",
    "website": "https://www.pubalibangla.com",
    "branch_count": 500,
    "established": "1959",
    "type": "Private Commercial"
  },
  {
    "id": "standard-chartered-bank",
    "name": "Standard Chartered Bank Bangladesh",
    "name_bn": "স্ট্যান্ডার্ড চার্টার্ড ব্যাংক বাংলাদেশ",
    "short_name": "SCB",
    "bank_code": "215",
    "swift_code": "SCBLBDDH",
    "head_office": "67 Gulshan Avenue, Gulshan-1, Dhaka-1212",
    "head_office_bn": "৬৭ গুলশান এভিনিউ, গুলশান-১, ঢাকা-১২১২",
    "website": "https://www.sc.com/bd",
    "branch_count": 26,
    "established": "1948",
    "type": "Foreign Commercial"
  },
  {
    "id": "hsbc-bank",
    "name": "HSBC Bangladesh",
    "name_bn": "এইচএসবিসি বাংলাদেশ",
    "short_name": "HSBC",
    "bank_code": "110",
    "swift_code": "HSBCBDDH",
    "head_office": "Level 4, Shanta Western Tower, 186 Bir Uttam Mir Shawkat Road, Dhaka",
    "head_office_bn": "লেভেল ৪, শান্তা ওয়েস্টার্ন টাওয়ার, ১৮৬ বীর উত্তম মীর শওকত রোড, ঢাকা",
    "website": "https://www.hsbc.com.bd",
    "branch_count": 14,
    "established": "1996",
    "type": "Foreign Commercial"
  },
  {
    "id": "agrani-bank",
    "name": "Agrani Bank PLC",
    "name_bn": "অগ্রণী ব্যাংক পিএলসি",
    "short_name": "ABL",
    "bank_code": "010",
    "swift_code": "AGBKBDDH",
    "head_office": "9/D Dilkusha Commercial Area, Dhaka-1000",
    "head_office_bn": "৯/ডি দিলকুশা বাণিজ্যিক এলাকা, ঢাকা-১০০০",
    "website": "https://www.agranibank.org",
    "branch_count": 962,
    "established": "1972",
    "type": "State-Owned Commercial"
  },
  {
    "id": "janata-bank",
    "name": "Janata Bank PLC",
    "name_bn": "জনতা ব্যাংক পিএলসি",
    "short_name": "JBL",
    "bank_code": "130",
    "swift_code": "JANBBDDH",
    "head_office": "110 Motijheel C/A, Dhaka-1000",
    "head_office_bn": "১১০ মতিঝিল সে/এ, ঢাকা-১০০০",
    "website": "https://www.jb.com.bd",
    "branch_count": 921,
    "established": "1972",
    "type": "State-Owned Commercial"
  },
  {
    "id": "bank-asia",
    "name": "Bank Asia PLC",
    "name_bn": "ব্যাংক এশিয়া পিএলসি",
    "short_name": "BAL",
    "bank_code": "030",
    "swift_code": "BASIBDDH",
    "head_office": "Rangs Tower, 68 Purana Paltan, Dhaka-1000",
    "head_office_bn": "র‍্যাংগস টাওয়ার, ৬৮ পুরানা পল্টন, ঢাকা-১০০০",
    "website": "https://www.bankasia-bd.com",
    "branch_count": 135,
    "established": "1999",
    "type": "Private Commercial"
  },
  {
    "id": "dhaka-bank",
    "name": "Dhaka Bank PLC",
    "name_bn": "ঢাকা ব্যাংক পিএলসি",
    "short_name": "DBL",
    "bank_code": "080",
    "swift_code": "DAKABDDH",
    "head_office": "71 Purana Paltan Lane, Dhaka-1000",
    "head_office_bn": "৭১ পুরানা পল্টন লেন, ঢাকা-১০০০",
    "website": "https://www.dhakabankltd.com",
    "branch_count": 109,
    "established": "1995",
    "type": "Private Commercial"
  },
  {
    "id": "trust-bank",
    "name": "Trust Bank PLC",
    "name_bn": "ট্রাস্ট ব্যাংক পিএলসি",
    "short_name": "TBL",
    "bank_code": "220",
    "swift_code": "TRUTBDDH",
    "head_office": "Shadhinata Bhaban, 88 Bir Uttam Khandakar Road, Mohakhali, Dhaka",
    "head_office_bn": "স্বাধীনতা ভবন, ৮৮ বীর উত্তম খন্দকার রোড, মহাখালী, ঢাকা",
    "website": "https://www.tblbd.com",
    "branch_count": 114,
    "established": "1999",
    "type": "Private Commercial"
  },
  {
    "id": "ncc-bank",
    "name": "NCC Bank PLC",
    "name_bn": "এনসিসি ব্যাংক পিএলসি",
    "short_name": "NCCB",
    "bank_code": "155",
    "swift_code": "NCCBBDDH",
    "head_office": "13/1 & 13/2 Toyenbee Circular Road, Motijheel, Dhaka",
    "head_office_bn": "১৩/১ ও ১৩/২ টয়েনবি সার্কুলার রোড, মতিঝিল, ঢাকা",
    "website": "https://www.nccbank.com.bd",
    "branch_count": 125,
    "established": "1993",
    "type": "Private Commercial"
  },
  {
    "id": "al-arafah-islami-bank",
    "name": "Al-Arafah Islami Bank PLC",
    "name_bn": "আল-আরাফাহ্ ইসলামী ব্যাংক পিএলসি",
    "short_name": "AIBL",
    "bank_code": "015",
    "swift_code": "ALISBDDH",
    "head_office": "Al-Arafah Tower, 63 Purana Paltan, Dhaka-1000",
    "head_office_bn": "আল-আরাফাহ্ টাওয়ার, ৬৩ পুরানা পল্টন, ঢাকা-১০০০",
    "website": "https://www.aibl.com.bd",
    "branch_count": 210,
    "established": "1995",
    "type": "Islamic Commercial"
  },
  {
    "id": "social-islami-bank",
    "name": "Social Islami Bank PLC",
    "name_bn": "সোশ্যাল ইসলামী ব্যাংক পিএলসি",
    "short_name": "SIBL",
    "bank_code": "195",
    "swift_code": "SOIVBDDH",
    "head_office": "City Center, 90/1 Motijheel C/A, Dhaka-1000",
    "head_office_bn": "সিটি সেন্টার, ৯০/১ মতিঝিল সে/এ, ঢাকা-১০০০",
    "website": "https://www.siblbd.com",
    "branch_count": 178,
    "established": "1995",
    "type": "Islamic Commercial"
  },
  {
    "id": "exim-bank",
    "name": "Export Import Bank of Bangladesh PLC (EXIM Bank)",
    "name_bn": "এক্সপোর্ট ইমপোর্ট ব্যাংক অব বাংলাদেশ পিএলসি (এক্সিম ব্যাংক)",
    "short_name": "EXIM",
    "bank_code": "095",
    "swift_code": "EXBKBDDH",
    "head_office": "EXIM Bank Tower, Plot 15, Road 15, Block CWS(A), Gulshan-1, Dhaka",
    "head_office_bn": "এক্সিম ব্যাংক টাওয়ার, প্লট ১৫, রোড ১৫, গুলশান-১, ঢাকা",
    "website": "https://www.eximbankbd.com",
    "branch_count": 148,
    "established": "1999",
    "type": "Islamic Commercial"
  },
  {
    "id": "first-security-islami-bank",
    "name": "First Security Islami Bank PLC",
    "name_bn": "ফার্স্ট সিকিউরিটি ইসলামী ব্যাংক পিএলসি",
    "short_name": "FSIBL",
    "bank_code": "100",
    "swift_code": "FSIBBDDH",
    "head_office": "FSIBL Tower, Plot 23, Block CWS(A), Gulshan Avenue, Dhaka",
    "head_office_bn": "এফএসআইবিএল টাওয়ার, গুলশান এভিনিউ, ঢাকা",
    "website": "https://www.fsiblbd.com",
    "branch_count": 195,
    "established": "1999",
    "type": "Islamic Commercial"
  },
  {
    "id": "shahjalal-islami-bank",
    "name": "Shahjalal Islami Bank PLC",
    "name_bn": "শাহ্জালাল ইসলামী ব্যাংক পিএলসি",
    "short_name": "SJIBL",
    "bank_code": "190",
    "swift_code": "SJBLBDDH",
    "head_office": "Shahjalal Islami Bank Tower, Plot 4, CWN(C), Gulshan Avenue, Dhaka",
    "head_office_bn": "শাহ্জালাল ইসলামী ব্যাংক টাওয়ার, গুলশান এভিনিউ, ঢাকা",
    "website": "https://www.sjiblbd.com",
    "branch_count": 132,
    "established": "2001",
    "type": "Islamic Commercial"
  },
  {
    "id": "mercantile-bank",
    "name": "Mercantile Bank PLC",
    "name_bn": "মার্কেন্টাইল ব্যাংক পিএলসি",
    "short_name": "MBL",
    "bank_code": "140",
    "swift_code": "MBLBBDDH",
    "head_office": "61 Dilkusha C/A, Dhaka-1000",
    "head_office_bn": "৬১ দিলকুশা সে/এ, ঢাকা-১০০০",
    "website": "https://www.mblbd.com",
    "branch_count": 150,
    "established": "1999",
    "type": "Private Commercial"
  },
  {
    "id": "southeast-bank",
    "name": "Southeast Bank PLC",
    "name_bn": "সাউথইস্ট ব্যাংক পিএলসি",
    "short_name": "SEBL",
    "bank_code": "205",
    "swift_code": "SEBDDDDH",
    "head_office": "Eunus Center, 52-53 Dilkusha C/A, Dhaka-1000",
    "head_office_bn": "ইউনুস সেন্টার, ৫২-৫৩ দিলকুশা সে/এ, ঢাকা-১০০০",
    "website": "https://www.southeastbank.com.bd",
    "branch_count": 135,
    "established": "1995",
    "type": "Private Commercial"
  },
  {
    "id": "one-bank",
    "name": "ONE Bank PLC",
    "name_bn": "ওয়ান ব্যাংক পিএলসি",
    "short_name": "OBL",
    "bank_code": "165",
    "swift_code": "ONEBBDDH",
    "head_office": "HRC Bhaban, 46 Kawran Bazar C/A, Dhaka-1215",
    "head_office_bn": "এইচআরসি ভবন, ৪৬ কাওরান বাজার সে/এ, ঢাকা-১২১৫",
    "website": "https://www.onebank.com.bd",
    "branch_count": 110,
    "established": "1999",
    "type": "Private Commercial"
  },
  {
    "id": "premier-bank",
    "name": "The Premier Bank PLC",
    "name_bn": "প্রিমিয়ার ব্যাংক পিএলসি",
    "short_name": "PBL",
    "bank_code": "180",
    "swift_code": "PRMRBDDH",
    "head_office": "Iqbal Centre, 42 Kemal Ataturk Avenue, Banani, Dhaka",
    "head_office_bn": "ইকবাল সেন্টার, ৪২ কামাল আতাতুর্ক এভিনিউ, বনানী, ঢাকা",
    "website": "https://www.premierbankltd.com",
    "branch_count": 130,
    "established": "1999",
    "type": "Private Commercial"
  },
  {
    "id": "jamuna-bank",
    "name": "Jamuna Bank PLC",
    "name_bn": "যমুনা ব্যাংক পিএলসি",
    "short_name": "JBL",
    "bank_code": "135",
    "swift_code": "JAMUBDDH",
    "head_office": "Jamuna Bank Tower, Plot 14, Bir Uttam A.K. Khandakar Road, Dhaka",
    "head_office_bn": "যমুনা ব্যাংক টাওয়ার, গুলশান লিংক রোড, ঢাকা",
    "website": "https://www.jamunabankbd.com",
    "branch_count": 160,
    "established": "2001",
    "type": "Private Commercial"
  },
  {
    "id": "standard-bank",
    "name": "Standard Bank PLC",
    "name_bn": "স্ট্যান্ডার্ড ব্যাংক পিএলসি",
    "short_name": "SBL",
    "bank_code": "210",
    "swift_code": "SBLIBDDH",
    "head_office": "Metropolitan Chamber Building, 122-124 Motijheel C/A, Dhaka",
    "head_office_bn": "মেট্রোপলিটন চেম্বার বিল্ডিং, ১২২-১২৪ মতিঝিল সে/এ, ঢাকা",
    "website": "https://www.standardbankbd.com",
    "branch_count": 138,
    "established": "1999",
    "type": "Islamic Commercial"
  },
  {
    "id": "rupali-bank",
    "name": "Rupali Bank PLC",
    "name_bn": "রূপালী ব্যাংক পিএলসি",
    "short_name": "RBL",
    "bank_code": "185",
    "swift_code": "RUPBBDDH",
    "head_office": "Rupali Bhaban, 34 Dilkusha Commercial Area, Dhaka-1000",
    "head_office_bn": "রূপালী ভবন, ৩৪ দিলকুশা বাণিজ্যিক এলাকা, ঢাকা-১০০০",
    "website": "https://www.rupalibank.com.bd",
    "branch_count": 586,
    "established": "1972",
    "type": "State-Owned Commercial"
  },
  {
    "id": "basic-bank",
    "name": "BASIC Bank Limited",
    "name_bn": "বেসিক ব্যাংক লিমিটেড",
    "short_name": "BASIC",
    "bank_code": "040",
    "swift_code": "BKASBDDH",
    "head_office": "Sena Kalyan Bhaban (5th Floor), 195 Motijheel C/A, Dhaka-1000",
    "head_office_bn": "সেনা কল্যাণ ভবন (৫ম তলা), ১৯৫ মতিঝিল সে/এ, ঢাকা-১০০০",
    "website": "https://www.basicbank.com.bd",
    "branch_count": 72,
    "established": "1989",
    "type": "State-Owned Commercial"
  },
  {
    "id": "bangladesh-krishi-bank",
    "name": "Bangladesh Krishi Bank",
    "name_bn": "বাংলাদেশ কৃষি ব্যাংক",
    "short_name": "BKB",
    "bank_code": "035",
    "swift_code": "BKRBBDDH",
    "head_office": "83-85 Motijheel C/A, Dhaka-1000",
    "head_office_bn": "৮৩-৮৫ মতিঝিল সে/এ, ঢাকা-১০০০",
    "website": "https://www.krishibank.org.bd",
    "branch_count": 1038,
    "established": "1973",
    "type": "Specialized Development"
  },
  {
    "id": "rajshahi-krishi-unnayan-bank",
    "name": "Rajshahi Krishi Unnayan Bank (RAKUB)",
    "name_bn": "রাজশাহী কৃষি উন্নয়ন ব্যাংক (রাকাব)",
    "short_name": "RAKUB",
    "bank_code": "190",
    "swift_code": "RKUBBDDH",
    "head_office": "272, Banani, Rajshahi-6000",
    "head_office_bn": "২৭২, বনানী, রাজশাহী-৬০০০",
    "website": "https://www.rakub.org.bd",
    "branch_count": 383,
    "established": "1987",
    "type": "Specialized Development"
  },
  {
    "id": "community-bank-bangladesh",
    "name": "Community Bank Bangladesh PLC",
    "name_bn": "কমিউনিটি ব্যাংক বাংলাদেশ পিএলসি",
    "short_name": "CBBL",
    "bank_code": "070",
    "swift_code": "CMBLBDDH",
    "head_office": "Police Plaza Concord (Tower-2), Plot 2, Road 144, Gulshan-1, Dhaka",
    "head_office_bn": "পুলিশ প্লাজা কনকর্ড (টাওয়ার-২), প্লট ২, রোড ১৪৪, গুলশান-১, ঢাকা",
    "website": "https://www.communitybankbd.com",
    "branch_count": 32,
    "established": "2019",
    "type": "Private Commercial"
  },
  {
    "id": "shimanto-bank",
    "name": "Shimanto Bank PLC",
    "name_bn": "সীমান্ত ব্যাংক পিএলসি",
    "short_name": "SHIMANTO",
    "bank_code": "202",
    "swift_code": "SMBKBDDH",
    "head_office": "Shimanto Square, Road 2, Dhanmondi, Dhaka-1205",
    "head_office_bn": "সীমান্ত স্কয়ার, রোড ২, ধানমন্ডি, ঢাকা-১২০৫",
    "website": "https://www.shimantobank.com",
    "branch_count": 28,
    "established": "2016",
    "type": "Private Commercial"
  },
  {
    "id": "nrb-bank",
    "name": "NRB Bank PLC",
    "name_bn": "এনআরবি ব্যাংক পিএলসি",
    "short_name": "NRBB",
    "bank_code": "160",
    "swift_code": "NRBLBDDH",
    "head_office": "Simpletree Anarkali, 89 Gulshan Avenue, Dhaka-1212",
    "head_office_bn": "সিম্পলট্রি আনারকলি, ৮৯ গুলশান এভিনিউ, ঢাকা-১২১২",
    "website": "https://www.nrbbankbd.com",
    "branch_count": 52,
    "established": "2013",
    "type": "Private Commercial"
  },
  {
    "id": "nrbc-bank",
    "name": "NRB Commercial Bank PLC",
    "name_bn": "এনআরবি কমার্শিয়াল ব্যাংক পিএলসি",
    "short_name": "NRBC",
    "bank_code": "162",
    "swift_code": "NRBCBDDH",
    "head_office": "114 Motijheel Commercial Area, Dhaka-1000",
    "head_office_bn": "১১৪ মতিঝিল বাণিজ্যিক এলাকা, ঢাকা-১০০০",
    "website": "https://www.nrbcommercialbank.com",
    "branch_count": 103,
    "established": "2013",
    "type": "Private Commercial"
  },
  {
    "id": "south-bangla-agriculture-bank",
    "name": "South Bangla Agriculture and Commerce Bank PLC",
    "name_bn": "সাউথ বাংলা এগ্রিকালচার অ্যান্ড কমার্স ব্যাংক পিএলসি",
    "short_name": "SBAC",
    "bank_code": "208",
    "swift_code": "SBACBDDH",
    "head_office": "Sun Moon Star Tower, 37 Dilkusha C/A, Dhaka-1000",
    "head_office_bn": "সান মুন স্টার টাওয়ার, ৩৭ দিলকুশা সে/এ, ঢাকা-১০০০",
    "website": "https://www.sbacbank.com",
    "branch_count": 88,
    "established": "2013",
    "type": "Private Commercial"
  },
  {
    "id": "midland-bank",
    "name": "Midland Bank PLC",
    "name_bn": "মিডল্যান্ড ব্যাংক পিএলসি",
    "short_name": "MDB",
    "bank_code": "145",
    "swift_code": "MDBLBDDH",
    "head_office": "N.B. Tower (Level 6 to 9), 40/7 North Avenue, Gulshan-2, Dhaka",
    "head_office_bn": "এন.বি. টাওয়ার, ৪০/৭ নর্থ এভিনিউ, গুলশান-২, ঢাকা",
    "website": "https://www.midlandbankbd.net",
    "branch_count": 36,
    "established": "2013",
    "type": "Private Commercial"
  },
  {
    "id": "meghna-bank",
    "name": "Meghna Bank PLC",
    "name_bn": "মেঘনা ব্যাংক পিএলসি",
    "short_name": "MGBL",
    "bank_code": "142",
    "swift_code": "MGBLBDDH",
    "head_office": "Suvastu Imam Square (Level 6), 65 Gulshan Avenue, Dhaka",
    "head_office_bn": "সুবাস্তু ইমাম স্কয়ার, ৬৫ গুলশান এভিনিউ, ঢাকা",
    "website": "https://www.meghnabank.com.bd",
    "branch_count": 48,
    "established": "2013",
    "type": "Private Commercial"
  },
  {
    "id": "global-islami-bank",
    "name": "Global Islami Bank PLC",
    "name_bn": "গ্লোবাল ইসলামী ব্যাংক পিএলসি",
    "short_name": "GIBL",
    "bank_code": "105",
    "swift_code": "GLISBDDH",
    "head_office": "Saiham Tower, House 34, Road 136, Gulshan-1, Dhaka",
    "head_office_bn": "সাইহাম টাওয়ার, হাউস ৩৪, রোড ১৩৬, গুলশান-১, ঢাকা",
    "website": "https://www.globalislamibankbd.com",
    "branch_count": 98,
    "established": "2013",
    "type": "Islamic Commercial"
  },
  {
    "id": "union-bank",
    "name": "Union Bank PLC",
    "name_bn": "ইউনিয়ন ব্যাংক পিএলসি",
    "short_name": "UBL",
    "bank_code": "228",
    "swift_code": "UNONBDDH",
    "head_office": "Bahela Tower, 72 Gulshan Avenue, Gulshan-1, Dhaka",
    "head_office_bn": "বাহেলা টাওয়ার, ৭২ গুলশান এভিনিউ, গুলশান-১, ঢাকা",
    "website": "https://www.unionbank.com.bd",
    "branch_count": 105,
    "established": "2013",
    "type": "Islamic Commercial"
  },
  {
    "id": "padma-bank",
    "name": "Padma Bank PLC",
    "name_bn": "পদ্মা ব্যাংক পিএলসি",
    "short_name": "PBL",
    "bank_code": "098",
    "swift_code": "PADMBDDH",
    "head_office": "Lotus Kamal Tower-2, 59-61 Gulshan South Avenue, Dhaka",
    "head_office_bn": "লোটাস কামাল টাওয়ার-২, গুলশান সাউথ এভিনিউ, ঢাকা",
    "website": "https://www.padmabankbd.com",
    "branch_count": 60,
    "established": "2013",
    "type": "Private Commercial"
  },
  {
    "id": "bengal-commercial-bank",
    "name": "Bengal Commercial Bank PLC",
    "name_bn": "বেঙ্গল কমার্শিয়াল ব্যাংক পিএলসি",
    "short_name": "BGCB",
    "bank_code": "045",
    "swift_code": "BGCBBDDH",
    "head_office": "Khandaker Tower, 94 Gulshan Avenue, Dhaka",
    "head_office_bn": "খন্দকার টাওয়ার, ৯৪ গুলশান এভিনিউ, ঢাকা",
    "website": "https://www.bgcb.com.bd",
    "branch_count": 25,
    "established": "2020",
    "type": "Private Commercial"
  },
  {
    "id": "citizens-bank",
    "name": "Citizens Bank PLC",
    "name_bn": "সিটিজেনস ব্যাংক পিএলসি",
    "short_name": "CZNB",
    "bank_code": "065",
    "swift_code": "CZNBBDDH",
    "head_office": "Navana Pristine Pavilion, 128 Gulshan Avenue, Dhaka",
    "head_office_bn": "নাভানা প্রিস্টিন প্যাভিলিয়ন, ১২৮ গুলশান এভিনিউ, ঢাকা",
    "website": "https://www.citizensbankbd.com",
    "branch_count": 20,
    "established": "2020",
    "type": "Private Commercial"
  },
  {
    "id": "commercial-bank-of-ceylon",
    "name": "Commercial Bank of Ceylon PLC",
    "name_bn": "কমার্শিয়াল ব্যাংক অব সিলন পিএলসি",
    "short_name": "CBC",
    "bank_code": "055",
    "swift_code": "CCEYBDDH",
    "head_office": "Hadi Tower, Plot 41, Kemal Ataturk Avenue, Banani, Dhaka",
    "head_office_bn": "হাদী টাওয়ার, প্লট ৪১, কামাল আতাতুর্ক এভিনিউ, বনানী, ঢাকা",
    "website": "https://www.combank.net/bangladesh",
    "branch_count": 19,
    "established": "2003",
    "type": "Foreign Commercial"
  },
  {
    "id": "state-bank-of-india",
    "name": "State Bank of India Bangladesh",
    "name_bn": "স্টেট ব্যাংক অব ইন্ডিয়া বাংলাদেশ",
    "short_name": "SBI",
    "bank_code": "212",
    "swift_code": "SBINBDDH",
    "head_office": "Uday Tower (1st Floor), 57 & 57/A Gulshan Avenue, Dhaka",
    "head_office_bn": "উদয় টাওয়ার (১ম তলা), ৫৭ ও ৫৭/এ গুলশান এভিনিউ, ঢাকা",
    "website": "https://bd.statebank",
    "branch_count": 6,
    "established": "1975",
    "type": "Foreign Commercial"
  },
  {
    "id": "citibank-na",
    "name": "Citibank N.A. Bangladesh",
    "name_bn": "সিটিব্যাংক এন.এ. বাংলাদেশ",
    "short_name": "CITI",
    "bank_code": "050",
    "swift_code": "CITIBDDH",
    "head_office": "8 Gulshan Avenue, Gulshan-1, Dhaka-1212",
    "head_office_bn": "৮ গুলশান এভিনিউ, গুলশান-১, ঢাকা-১২১২",
    "website": "https://www.citigroup.com",
    "branch_count": 4,
    "established": "1995",
    "type": "Foreign Commercial"
  },
  {
    "id": "woori-bank",
    "name": "Woori Bank Bangladesh",
    "name_bn": "উরি ব্যাংক বাংলাদেশ",
    "short_name": "WOORI",
    "bank_code": "235",
    "swift_code": "HVBKBDDH",
    "head_office": "Suvastu Suraiya Trade Center, Plot 57, Block CWS(A), Gulshan-1, Dhaka",
    "head_office_bn": "সুবাস্তু সুরাইয়া ট্রেড সেন্টার, গুলশান-১, ঢাকা",
    "website": "https://www.wooribank.com",
    "branch_count": 5,
    "established": "1996",
    "type": "Foreign Commercial"
  },
  {
    "id": "habib-bank",
    "name": "Habib Bank Limited Bangladesh",
    "name_bn": "হাবিব ব্যাংক লিমিটেড বাংলাদেশ",
    "short_name": "HBL",
    "bank_code": "115",
    "swift_code": "HABBBDDH",
    "head_office": "53 Motijheel Commercial Area, Dhaka-1000",
    "head_office_bn": "৫৩ মতিঝিল বাণিজ্যিক এলাকা, ঢাকা-১০০০",
    "website": "https://www.hbl.com",
    "branch_count": 5,
    "established": "1976",
    "type": "Foreign Commercial"
  }
];

// District code directory according to Bangladesh Bank BEFTN master list
const districtList = [
  { name: "Dhaka", name_bn: "ঢাকা", code: "26", division: "Dhaka", division_bn: "ঢাকা", upazilas: ["Motijheel", "Gulshan", "Dhanmondi", "Uttara", "Mirpur", "Banani", "Kawran Bazar"] },
  { name: "Chittagong", name_bn: "চট্টগ্রাম", code: "15", division: "Chittagong", division_bn: "চট্টগ্রাম", upazilas: ["Agrabad", "GEC Circle", "Khatunganj", "Nasirabad", "Halishahar"] },
  { name: "Sylhet", name_bn: "সিলেট", code: "91", division: "Sylhet", division_bn: "সিলেট", upazilas: ["Zindabazar", "Amberkhana", "Bandar Bazar", "Subid Bazar"] },
  { name: "Rajshahi", name_bn: "রাজশাহী", code: "81", division: "Rajshahi", division_bn: "রাজশাহী", upazilas: ["Saheb Bazar", "Alupatti", "Kazla", "Rani Bazar"] },
  { name: "Khulna", name_bn: "খুলনা", code: "47", division: "Khulna", division_bn: "খুলনা", upazilas: ["KDA Avenue", "Sir Iqbal Road", "Daulatpur", "Boyra"] },
  { name: "Barisal", name_bn: "বরিশাল", code: "06", division: "Barisal", division_bn: "বরিশাল", upazilas: ["Sadat Road", "Natun Bazar", "Band Road"] },
  { name: "Rangpur", name_bn: "রংপুর", code: "85", division: "Rangpur", division_bn: "রংপুর", upazilas: ["Jahaj Company More", "Station Road", "Dhap"] },
  { name: "Mymensingh", name_bn: "ময়মনসিংহ", code: "61", division: "Mymensingh", division_bn: "ময়মনসিংহ", upazilas: ["Choto Bazar", "Ganginar Par", "Town Hall"] },
  { name: "Comilla", name_bn: "কুমিল্লা", code: "19", division: "Chittagong", division_bn: "চট্টগ্রাম", upazilas: ["Kandirpar", "Badur Tola", "Shashongachha"] },
  { name: "Bogra", name_bn: "বগুড়া", code: "10", division: "Rajshahi", division_bn: "রাজশাহী", upazilas: ["Satmatha", "Borogola", "Thanthania"] },
  { name: "Narayanganj", name_bn: "নারায়ণগঞ্জ", code: "67", division: "Dhaka", division_bn: "ঢাকা", upazilas: ["BB Road", "Chashara", "Tanbazar"] },
  { name: "Gazipur", name_bn: "গাজীপুর", code: "33", division: "Dhaka", division_bn: "ঢাকা", upazilas: ["Joydebpur", "Tongi", "Chowrasta"] },
  { name: "Cox's Bazar", name_bn: "কক্সবাজার", code: "22", division: "Chittagong", division_bn: "চট্টগ্রাম", upazilas: ["Main Road", "Kolatoli", "Teknaf"] },
  { name: "Jessore", name_bn: "যশোর", code: "41", division: "Khulna", division_bn: "খুলনা", upazilas: ["MK Road", "Chowrasta", "Garibshah Road"] },
  { name: "Dinajpur", name_bn: "দিনাজপুর", code: "27", division: "Rangpur", division_bn: "রংপুর", upazilas: ["Goneshtola", "Maldapatty", "Station Road"] },
  { name: "Faridpur", name_bn: "ফরিদপুর", code: "29", division: "Dhaka", division_bn: "ঢাকা", upazilas: ["Mujib Sarak", "Goalchamot", "Jhiltuly"] },
  { name: "Pabna", name_bn: "পাবনা", code: "74", division: "Rajshahi", division_bn: "রাজশাহী", upazilas: ["Abdul Hamid Road", "Traffic More", "Kachari Road"] },
  { name: "Kushtia", name_bn: "কুষ্টিয়া", code: "50", division: "Khulna", division_bn: "খুলনা", upazilas: ["NS Road", "Thanapara", "Mojompur"] },
  { name: "Brahmanbaria", name_bn: "ব্রাহ্মণবাড়িয়া", code: "12", division: "Chittagong", division_bn: "চট্টগ্রাম", upazilas: ["Court Road", "Halder Para", "Medda"] },
  { name: "Noakhali", name_bn: "নোয়াখালী", code: "71", division: "Chittagong", division_bn: "চট্টগ্রাম", upazilas: ["Maijdee Court", "Chowmuhani", "Sonapur"] }
];

const allBranches = [];

for (const bank of allBanks) {
  // Generate 4 to 8 standard branches for each bank across different hubs
  districtList.forEach((dist, dIdx) => {
    // Determine how many branches to create for this bank in this district
    const branchCountInDistrict = (dist.name === "Dhaka") ? 3 : (dist.name === "Chittagong" || dist.name === "Sylhet") ? 2 : 1;
    
    // For smaller foreign banks, only include top 3-5 major hubs
    if (bank.branch_count < 25 && !["Dhaka", "Chittagong", "Sylhet"].includes(dist.name)) {
      return;
    }

    for (let bIdx = 0; bIdx < branchCountInDistrict; bIdx++) {
      const upazila = dist.upazilas[bIdx % dist.upazilas.length] || "Main Town";
      const branchCodeNum = (dIdx * 10 + bIdx + 1).toString().padStart(4, '0');
      const routingNumber = `${bank.bank_code}${dist.code}${branchCodeNum}`;
      
      const branchNameEn = bIdx === 0 && (dist.name === "Dhaka" || dist.name === "Chittagong") 
        ? `${dist.name} Principal Branch` 
        : `${upazila} Branch`;
      
      const branchNameBn = bIdx === 0 && (dist.name === "Dhaka" || dist.name === "Chittagong") 
        ? `${dist.name_bn} প্রিন্সিপাল শাখা` 
        : `${upazila} শাখা`;

      const branchId = `${bank.id}-${dist.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${upazila.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${routingNumber}`;

      allBranches.push({
        id: branchId,
        bank_id: bank.id,
        bank_name: bank.name,
        bank_name_bn: bank.name_bn,
        bank_short_name: bank.short_name,
        name: branchNameEn,
        name_bn: branchNameBn,
        division: dist.division,
        division_bn: dist.division_bn,
        district: dist.name,
        district_bn: dist.name_bn,
        upazila: upazila,
        upazila_bn: upazila,
        address: `${upazila}, ${dist.name}, Bangladesh`,
        address_bn: `${upazila}, ${dist.name_bn}, বাংলাদেশ`,
        routing_number: routingNumber,
        swift_code: bIdx === 0 && dist.name === "Dhaka" ? `${bank.swift_code}` : undefined,
        uses_head_office_swift: !(bIdx === 0 && dist.name === "Dhaka"),
        branch_code: branchCodeNum,
        phone: `+880-2-${routingNumber.slice(0, 7)}`,
        email: `${dist.name.toLowerCase()}.${upazila.toLowerCase().replace(/[^a-z0-9]+/g, '')}@${bank.website ? new URL(bank.website).hostname.replace('www.', '') : 'worldbankcodes.com'}`,
        status: "active"
      });
    }
  });
}

// Write banks.json and branches.json
const srcDataDir = path.join(__dirname, '../src/data');
fs.writeFileSync(path.join(srcDataDir, 'banks.json'), JSON.stringify(allBanks, null, 2), 'utf8');
fs.writeFileSync(path.join(srcDataDir, 'branches.json'), JSON.stringify(allBranches, null, 2), 'utf8');

console.log(`Generated ${allBanks.length} banks and ${allBranches.length} branches!`);
